name: Build

on:
  push:
    branches:
      - post-tachi
    paths-ignore:
      - "**.md"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: null2264/actions/gradle-setup@b697b0b95bb90ab23c1145b744dddd2fd3e3a838
        with:
          java: 17
          distro: adopt

      - name: Build app
        run: ./gradlew assemble
